name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        config: kind.yaml

    - name: Get kubebuilder
      uses: RyanSiu1995/kubebuilder-action@v1.3.1
      with:
        version: 3.1.0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Download dependancies
      run: go mod download

    - name: Test
      run: go test -v -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...

    - name: coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: false # optional (default = false)
        verbose: false # optional (default = false)
